import { createBrowserRouter, Navigate, type RouteObject } from 'react-router-dom';

import { LoadingScreen } from '@/components/loading-screen';
import { ProtectedRoute } from '@/components/protected-route';
import { AppLayout } from '@/layouts/app-layout';

import { AccessDeniedPage } from '@/pages/auth/access-denied';
import { ForgotPasswordPage } from '@/pages/auth/forgot-password';
import { LoginPage } from '@/pages/auth/login';
import { RegisterPage } from '@/pages/auth/register';
import { SessionExpiredPage } from '@/pages/auth/session-expired';


import { DashboardPage } from '@/pages/dashboard';
import {
  DocumentListPage,
  DocumentFoldersPage,
  DocumentTagsPage,
  OcrQueuePage,
  DigitalSignaturesPage,
  DocumentCompliancePage,
} from '@/pages/dms';
import { ErrorPage } from '@/pages/error-page';
import {
  AccountGroupsPage,
  ChartOfAccountsPage,
  LedgerMasterPage,
  JournalEntriesPage,
  CashBookPage,
  BankBookPage,
  CostCentersPage,
  AccountingSettingsPage,
} from '@/pages/finance';
import {
  CreateAccountGroupPage,
  CreateChartOfAccountPage,
  CreateLedgerPage,
  CreateJournalEntryPage,
  CreateCostCenterPage,
} from '@/pages/finance/dynamic-forms';
import {
  GlEntriesPage,
  PostingRulesPage,
  FiscalClosingPage,
  TrialBalancePage,
  ProfitLossPage,
  BalanceSheetPage,
  CashFlowPage,
  DayBookPage,
  AccountStatementPage,
} from '@/pages/gl';
import {
  CreateGlEntryPage,
  CreatePostingRulePage,
  CreateFiscalClosingPage,
} from '@/pages/gl/dynamic-forms';
import {
  GstRegistrationsPage,
  GstLedgerPage,
  GstReturnsPage,
  TaxPostingsPage,
  YearClosingPage,
  PeriodLocksPage,
  OpeningBalanceTransfersPage,
  YearEndEntriesPage,
  AuditDetailsPage,
  NumberSeriesPage,
  VoucherApprovalsPage,
  GstAuditSettingsPage,
} from '@/pages/gst_audit';
import {
  CreateGstRegistrationPage,
  CreateTaxPostingPage,
  CreateNumberSeriesPage,
} from '@/pages/gst_audit/dynamic-forms';
import {
  ItemsPage,
  ItemGroupsPage,
  ItemVariantsPage,
  ItemPricingPage,
  ItemBarcodesPage,
  HsnCodesPage,
  StockOpeningPage,
  ItemImagesPage,
  InventorySettingsPage,
  BatchesPage,
  StockMovementsPage,
  WarehouseLocationsPage,
  NearExpiryPage,
  DamageRegisterPage,
  RecallRegisterPage,
  DistributorReturnsPage,
  ReplacementQueuePage,
  InventorySummaryPage,
  StockLedgerPage,
  BatchLedgerPage,
  ExpiryReportPage,
  MovementReportPage,
  ValuationReportPage,
  DeadStockPage,
  FastMovingPage,
  SlowMovingPage,
  BarcodeGenPage,
  ProductsPage,
  CreateProductPage,
  EditProductPage,
  ProductDetailPage,
  SubCategoriesPage,
  NewStockEntryPage,
  StockAdjustmentPage,
  StockLedgerEnhancedPage,
  LocationTreePage,
  StockTransfersPage,
  CreateTransferPage,
  StockReservationPage,
  WarehouseReportsPage,
} from '@/pages/inventory';
import {
  CompaniesPage,
  FinancialYearsPage,
  BranchesPage,
  WarehousesPage,
  UnitsPage,
  CategoriesPage,
  BrandsPage,
  TaxGroupsPage,
  GSTRatesPage,
  CreateCompanyPage,
  EditCompanyPage,
  CreateFinancialYearPage,
  EditFinancialYearPage,
  CreateBranchPage,
  EditBranchPage,
  CreateWarehousePage,
  EditWarehousePage,
  CreateUnitPage,
  EditUnitPage,
  CreateCategoryPage,
  EditCategoryPage,
  CreateBrandPage,
  EditBrandPage,
  CreateTaxGroupPage,
  EditTaxGroupPage,
  CreateGstRatePage,
  EditGstRatePage,
} from '@/pages/masters';
import { NotFoundPage } from '@/pages/not-found-page';
import {
  PurchaseOrdersPage,
  PurchaseQuotationsPage,
  GrnPage,
  PurchaseInvoicesPage,
  PurchaseReturnsPage,
  SupplierPriceListPage,
  PurchaseApprovalsPage,
  PurchaseSettingsPage,
  SuppliersPage,
  CreateSupplierPage,
  EditSupplierPage,
  PurchaseRequisitionsPage,
  PurchaseRegisterReport,
  GrnRegisterReport,
  PendingPOReport,
  PurchaseReturnReport,
  GstPurchaseReport,
} from '@/pages/purchase';

import {
  SalesQuotationsPage,
  SalesOrdersPage,
  DeliveryChallansPage,
  SalesInvoicesPage,
  CreateSalesInvoicePage,
  SalesReturnsPage,
  CustomerPriceListPage,
  SalesApprovalsPage,
  SalesSettingsPage,
  CustomersPage,
  CreateCustomerPage,
  EditCustomerPage,
} from '@/pages/sales';
import {
  SalesReportsDashboardPage,
  SalesRegisterReport,
  InvoiceRegisterReport,
  CustomerLedgerReport,
  ProductSalesReport,
  OutstandingReport,
  GstReport,
  PaymentReport,
  ProfitAnalysisReport,
  ExportCenter,
} from '@/pages/sales/reports';
import {
  ApprovalsPage,
  ApprovalDashboard,
  ApprovalSettings,
} from '@/pages/sales/approvals';
import {
  CreditDashboardPage,
  CreditCustomersPage,
  AgeingReportPage,
  RecoveryDashboardPage,
  CreditHoldDashboardPage,
  ReminderEnginePage,
} from '@/pages/sales/credit';
import {
  CreateReturnPage,
  CreditNotesPage,
  DebitNotesPage,
  ReturnReportsPage,
} from '@/pages/sales/returns';
import { ApprovalDashboardPage, PendingTasksDashboardPage, MyTasksDashboardPage, EscalationDashboardPage } from '@/pages/workflow';

const routes: RouteObject[] = [
  {
    path: '/',
    element: (
      <ProtectedRoute>
        <AppLayout />
      </ProtectedRoute>
    ),
    errorElement: <ErrorPage />,
    hydrateFallbackElement: <LoadingScreen />,
    children: [
      {
        index: true,
        element: <DashboardPage />,
      },
      // ── Master Data Modules ──────────────────────────
      // ── Master Data List Routes ────────────────────
      { path: 'companies', element: <CompaniesPage /> },
      { path: 'companies/create', element: <CreateCompanyPage /> },
      { path: 'companies/:id/edit', element: <EditCompanyPage /> },
      { path: 'financial-years', element: <FinancialYearsPage /> },
      { path: 'financial-years/create', element: <CreateFinancialYearPage /> },
      { path: 'financial-years/:id/edit', element: <EditFinancialYearPage /> },
      { path: 'branches', element: <BranchesPage /> },
      { path: 'branches/create', element: <CreateBranchPage /> },
      { path: 'branches/:id/edit', element: <EditBranchPage /> },
      { path: 'warehouses', element: <WarehousesPage /> },
      { path: 'warehouses/create', element: <CreateWarehousePage /> },
      { path: 'warehouses/:id/edit', element: <EditWarehousePage /> },
      { path: 'units', element: <UnitsPage /> },
      { path: 'units/create', element: <CreateUnitPage /> },
      { path: 'units/:id/edit', element: <EditUnitPage /> },
      { path: 'categories', element: <CategoriesPage /> },
      { path: 'categories/create', element: <CreateCategoryPage /> },
      { path: 'categories/:id/edit', element: <EditCategoryPage /> },
      { path: 'brands', element: <BrandsPage /> },
      { path: 'brands/create', element: <CreateBrandPage /> },
      { path: 'brands/:id/edit', element: <EditBrandPage /> },
      { path: 'tax-groups', element: <TaxGroupsPage /> },
      { path: 'tax-groups/create', element: <CreateTaxGroupPage /> },
      { path: 'tax-groups/:id/edit', element: <EditTaxGroupPage /> },
      { path: 'gst-rates', element: <GSTRatesPage /> },
      { path: 'gst-rates/create', element: <CreateGstRatePage /> },
      { path: 'gst-rates/:id/edit', element: <EditGstRatePage /> },
      // ── Inventory Modules ───────────────────────────
      { path: 'inventory/products', element: <ProductsPage /> },
      { path: 'inventory/products/create', element: <CreateProductPage /> },
      { path: 'inventory/products/:id/edit', element: <EditProductPage /> },
      { path: 'inventory/products/:id', element: <ProductDetailPage /> },
      { path: 'inventory/items', element: <ItemsPage /> },
      { path: 'inventory/groups', element: <ItemGroupsPage /> },
      { path: 'inventory/variants', element: <ItemVariantsPage /> },
      { path: 'inventory/pricing', element: <ItemPricingPage /> },
      { path: 'inventory/barcodes', element: <ItemBarcodesPage /> },
      { path: 'inventory/hsn-codes', element: <HsnCodesPage /> },
      { path: 'inventory/stock-opening', element: <StockOpeningPage /> },
      { path: 'inventory/sub-categories', element: <SubCategoriesPage /> },
      { path: 'inventory/images', element: <ItemImagesPage /> },
      { path: 'inventory/settings', element: <InventorySettingsPage /> },
      // ── PRM-015: Enterprise Inventory Engine ────
      { path: 'inventory/batches', element: <BatchesPage /> },
      { path: 'inventory/stock-entry', element: <NewStockEntryPage /> },
      { path: 'inventory/stock-adjustment', element: <StockAdjustmentPage /> },
      { path: 'inventory/ledger', element: <StockLedgerEnhancedPage /> },
      { path: 'inventory/stock-movements', element: <StockMovementsPage /> },
      { path: 'inventory/warehouse-dashboard', element: <Navigate to="/" replace /> },
      { path: 'inventory/warehouse-locations', element: <WarehouseLocationsPage /> },
      { path: 'inventory/location-tree', element: <LocationTreePage /> },
      { path: 'inventory/stock-transfers', element: <StockTransfersPage /> },
      { path: 'inventory/create-transfer', element: <CreateTransferPage /> },
      { path: 'inventory/stock-reservation', element: <StockReservationPage /> },
      { path: 'inventory/near-expiry', element: <NearExpiryPage /> },
      { path: 'inventory/damage-register', element: <DamageRegisterPage /> },
      { path: 'inventory/recall-register', element: <RecallRegisterPage /> },
      { path: 'inventory/distributor-returns', element: <DistributorReturnsPage /> },
      { path: 'inventory/replacement-queue', element: <ReplacementQueuePage /> },
      { path: 'inventory/reports/summary', element: <InventorySummaryPage /> },
      { path: 'inventory/reports/stock-ledger', element: <StockLedgerPage /> },
      { path: 'inventory/reports/batch-ledger', element: <BatchLedgerPage /> },
      { path: 'inventory/reports/expiry', element: <ExpiryReportPage /> },
      { path: 'inventory/reports/movement', element: <MovementReportPage /> },
      { path: 'inventory/reports/valuation', element: <ValuationReportPage /> },
      { path: 'inventory/reports/warehouse', element: <WarehouseReportsPage /> },
      { path: 'inventory/reports/dead-stock', element: <DeadStockPage /> },
      { path: 'inventory/reports/fast-moving', element: <FastMovingPage /> },
      { path: 'inventory/reports/slow-moving', element: <SlowMovingPage /> },
      { path: 'inventory/barcode-gen', element: <BarcodeGenPage /> },
      // ── Purchase Modules ────────────────────────────
      { path: 'purchase/dashboard', element: <Navigate to="/" replace /> },
      { path: 'purchase/orders', element: <PurchaseOrdersPage /> },
      { path: 'purchase/quotations', element: <PurchaseQuotationsPage /> },
      { path: 'purchase/grn', element: <GrnPage /> },
      { path: 'purchase/invoices', element: <PurchaseInvoicesPage /> },
      { path: 'purchase/returns', element: <PurchaseReturnsPage /> },
      { path: 'purchase/supplier-prices', element: <SupplierPriceListPage /> },
      { path: 'purchase/approvals', element: <PurchaseApprovalsPage /> },
      { path: 'purchase/settings', element: <PurchaseSettingsPage /> },
      { path: 'suppliers', element: <SuppliersPage /> },
      { path: 'suppliers/create', element: <CreateSupplierPage /> },
      { path: 'suppliers/:id/edit', element: <EditSupplierPage /> },
      { path: 'purchase/requisitions', element: <PurchaseRequisitionsPage /> },
      { path: 'purchase/reports/purchase-register', element: <PurchaseRegisterReport /> },
      { path: 'purchase/reports/grn-register', element: <GrnRegisterReport /> },
      { path: 'purchase/reports/pending-pos', element: <PendingPOReport /> },
      { path: 'purchase/reports/purchase-returns', element: <PurchaseReturnReport /> },
      { path: 'purchase/reports/gst-purchase', element: <GstPurchaseReport /> },
      // ── Sales Modules ──────────────────────────────
      { path: 'sales/dashboard', element: <Navigate to="/" replace /> },
      { path: 'sales/quotations', element: <SalesQuotationsPage /> },
      { path: 'sales/orders', element: <SalesOrdersPage /> },
      { path: 'sales/delivery-challans', element: <DeliveryChallansPage /> },
      { path: 'sales/invoices', element: <SalesInvoicesPage /> },
      { path: 'sales/invoices/create', element: <CreateSalesInvoicePage /> },
      { path: 'sales/returns', element: <SalesReturnsPage /> },
      { path: 'sales/customer-prices', element: <CustomerPriceListPage /> },
      { path: 'sales/approvals/legacy', element: <SalesApprovalsPage /> },
      { path: 'customers', element: <CustomersPage /> },
      { path: 'customers/create', element: <CreateCustomerPage /> },
      { path: 'customers/:id/edit', element: <EditCustomerPage /> },
      { path: 'sales/settings', element: <SalesSettingsPage /> },
      // ── Sales Reports ────────────────────────────
      { path: 'sales/reports/dashboard', element: <SalesReportsDashboardPage /> },
      { path: 'sales/reports/register', element: <SalesRegisterReport /> },
      { path: 'sales/reports/invoices', element: <InvoiceRegisterReport /> },
      { path: 'sales/reports/customer-ledger', element: <CustomerLedgerReport /> },
      { path: 'sales/reports/products', element: <ProductSalesReport /> },
      { path: 'sales/reports/outstanding', element: <OutstandingReport /> },
      { path: 'sales/reports/gst', element: <GstReport /> },
      { path: 'sales/reports/payment', element: <PaymentReport /> },
      { path: 'sales/reports/profit', element: <ProfitAnalysisReport /> },
      { path: 'sales/reports/export', element: <ExportCenter /> },
      // ── Sales Approval Workflow (Step 11) ────────────
      { path: 'sales/approvals', element: <ApprovalsPage /> },
      { path: 'sales/approvals/dashboard', element: <ApprovalDashboard /> },
      { path: 'sales/approvals/settings', element: <ApprovalSettings /> },
      // ── Sales Credit Control (Step 12) ────────────
      { path: 'sales/credit/dashboard', element: <CreditDashboardPage /> },
      { path: 'sales/credit/customers', element: <CreditCustomersPage /> },
      { path: 'sales/credit/ageing', element: <AgeingReportPage /> },
      { path: 'sales/credit/recovery', element: <RecoveryDashboardPage /> },
      { path: 'sales/credit/credit-hold', element: <CreditHoldDashboardPage /> },
      { path: 'sales/credit/reminders', element: <ReminderEnginePage /> },
      // ── Sales Returns Engine (Step 13) ────────────
      { path: 'sales/returns/create', element: <CreateReturnPage /> },
      { path: 'sales/returns/credit-notes', element: <CreditNotesPage /> },
      { path: 'sales/returns/debit-notes', element: <DebitNotesPage /> },
      { path: 'sales/returns/reports', element: <ReturnReportsPage /> },
      // ── Finance Modules ────────────────────────────
      { path: 'finance/dashboard', element: <Navigate to="/" replace /> },
      { path: 'finance/account-groups', element: <AccountGroupsPage /> },
      { path: 'finance/account-groups/create', element: <CreateAccountGroupPage /> },
      { path: 'finance/account-groups/:id/edit', element: <CreateAccountGroupPage /> },
      { path: 'finance/chart-of-accounts', element: <ChartOfAccountsPage /> },
      { path: 'finance/chart-of-accounts/create', element: <CreateChartOfAccountPage /> },
      { path: 'finance/chart-of-accounts/:id/edit', element: <CreateChartOfAccountPage /> },
      { path: 'finance/ledgers', element: <LedgerMasterPage /> },
      { path: 'finance/ledgers/create', element: <CreateLedgerPage /> },
      { path: 'finance/ledgers/:id/edit', element: <CreateLedgerPage /> },
      { path: 'finance/journal-entries', element: <JournalEntriesPage /> },
      { path: 'finance/journal-entries/create', element: <CreateJournalEntryPage /> },
      { path: 'finance/journal-entries/:id/edit', element: <CreateJournalEntryPage /> },
      { path: 'finance/cash-book', element: <CashBookPage /> },
      { path: 'finance/bank-book', element: <BankBookPage /> },
      { path: 'finance/cost-centers', element: <CostCentersPage /> },
      { path: 'finance/cost-centers/create', element: <CreateCostCenterPage /> },
      { path: 'finance/cost-centers/:id/edit', element: <CreateCostCenterPage /> },
      { path: 'finance/settings', element: <AccountingSettingsPage /> },
      // ── GL / Reporting Modules ─────────────────────
      { path: 'gl/dashboard', element: <Navigate to="/" replace /> },
      { path: 'gl/entries', element: <GlEntriesPage /> },
      { path: 'gl/entries/create', element: <CreateGlEntryPage /> },
      { path: 'gl/entries/:id/edit', element: <CreateGlEntryPage /> },
      { path: 'gl/posting-rules', element: <PostingRulesPage /> },
      { path: 'gl/posting-rules/create', element: <CreatePostingRulePage /> },
      { path: 'gl/posting-rules/:id/edit', element: <CreatePostingRulePage /> },
      { path: 'gl/fiscal-closing', element: <FiscalClosingPage /> },
      { path: 'gl/fiscal-closing/create', element: <CreateFiscalClosingPage /> },
      { path: 'gl/fiscal-closing/:id/edit', element: <CreateFiscalClosingPage /> },
      { path: 'gl/trial-balance', element: <TrialBalancePage /> },
      { path: 'gl/profit-loss', element: <ProfitLossPage /> },
      { path: 'gl/balance-sheet', element: <BalanceSheetPage /> },
      { path: 'gl/cash-flow', element: <CashFlowPage /> },
      { path: 'gl/day-book', element: <DayBookPage /> },
      { path: 'gl/account-statement', element: <AccountStatementPage /> },
      // ── Automation Engine Modules ─────────────────
      { path: 'automation/posting', element: <Navigate to="/" replace /> },
      { path: 'automation/dashboard', element: <Navigate to="/" replace /> },
      { path: 'automation/monitor', element: <Navigate to="/" replace /> },
      { path: 'automation/integration', element: <Navigate to="/" replace /> },
      { path: 'automation/health', element: <Navigate to="/" replace /> },
      // ── GST, Audit & Financial Closing Modules ─────
      { path: 'gst/dashboard', element: <Navigate to="/" replace /> },
      { path: 'gst/analytics', element: <Navigate to="/" replace /> },
      { path: 'gst/registrations', element: <GstRegistrationsPage /> },
      { path: 'gst/ledger', element: <GstLedgerPage /> },
      { path: 'gst/returns', element: <GstReturnsPage /> },
      { path: 'gst/tax-postings', element: <TaxPostingsPage /> },
      { path: 'gst/year-closing', element: <YearClosingPage /> },
      { path: 'gst/period-locks', element: <PeriodLocksPage /> },
      { path: 'gst/opening-balance-transfers', element: <OpeningBalanceTransfersPage /> },
      { path: 'gst/year-end-entries', element: <YearEndEntriesPage /> },
      { path: 'gst/audit-details', element: <AuditDetailsPage /> },
      { path: 'gst/registrations/create', element: <CreateGstRegistrationPage /> },
      { path: 'gst/registrations/:id/edit', element: <CreateGstRegistrationPage /> },
      { path: 'gst/tax-postings/create', element: <CreateTaxPostingPage /> },
      { path: 'gst/tax-postings/:id/edit', element: <CreateTaxPostingPage /> },
      { path: 'gst/number-series', element: <NumberSeriesPage /> },
      { path: 'gst/number-series/create', element: <CreateNumberSeriesPage /> },
      { path: 'gst/voucher-approvals', element: <VoucherApprovalsPage /> },
      { path: 'gst/settings', element: <GstAuditSettingsPage /> },
    ],
  },      // ── Old dashboards — all redirect to main dashboard ──
      { path: 'executive/ceo', element: <Navigate to="/" replace /> },
      { path: 'executive/director', element: <Navigate to="/" replace /> },
      { path: 'executive/admin', element: <Navigate to="/" replace /> },
      { path: 'executive/operations', element: <Navigate to="/" replace /> },
      { path: 'executive/user', element: <Navigate to="/" replace /> },
      { path: 'bi/purchase', element: <Navigate to="/" replace /> },
      { path: 'bi/sales', element: <Navigate to="/" replace /> },
      { path: 'bi/inventory', element: <Navigate to="/" replace /> },
      { path: 'bi/finance', element: <Navigate to="/" replace /> },
      { path: 'bi/gst', element: <Navigate to="/" replace /> },
      { path: 'bi/customers', element: <Navigate to="/" replace /> },
      { path: 'bi/suppliers', element: <Navigate to="/" replace /> },
      { path: 'bi/warehouses', element: <Navigate to="/" replace /> },
      { path: 'bi/profitability', element: <Navigate to="/" replace /> },
      { path: 'bi/cash-flow', element: <Navigate to="/" replace /> },
      { path: 'bi/growth', element: <Navigate to="/" replace /> },
      { path: 'dms/dashboard', element: <Navigate to="/" replace /> },
      { path: 'dms/documents', element: <DocumentListPage /> },
      { path: 'dms/folders', element: <DocumentFoldersPage /> },
      { path: 'dms/tags', element: <DocumentTagsPage /> },
      { path: 'dms/ocr', element: <OcrQueuePage /> },
      { path: 'dms/signatures', element: <DigitalSignaturesPage /> },
      { path: 'dms/compliance', element: <DocumentCompliancePage /> },
      { path: 'workflow/dashboard', element: <Navigate to="/" replace /> },
      { path: 'workflow/approvals', element: <ApprovalDashboardPage /> },
      { path: 'workflow/tasks', element: <PendingTasksDashboardPage /> },
      { path: 'workflow/my-tasks', element: <MyTasksDashboardPage /> },
      { path: 'workflow/escalation', element: <EscalationDashboardPage /> },
      { path: 'ai/dashboard', element: <Navigate to="/" replace /> },
      { path: 'ai/insights', element: <Navigate to="/" replace /> },
      { path: 'ai/forecasts', element: <Navigate to="/" replace /> },
      { path: 'ai/usage', element: <Navigate to="/" replace /> },

      // ── Auth Routes ──────────────────────────────────
  {
    path: '/auth',
    children: [
      { path: 'login', element: <LoginPage /> },
      { path: 'register', element: <RegisterPage /> },
      { path: 'forgot-password', element: <ForgotPasswordPage /> },
      { path: 'access-denied', element: <AccessDeniedPage /> },
      { path: 'session-expired', element: <SessionExpiredPage /> },
    ],
  },
  {
    path: '*',
    element: <NotFoundPage />,
  },
];

export const router = createBrowserRouter(routes);
