import { jsx as _jsx } from "react/jsx-runtime";
import { createBrowserRouter, Navigate } from 'react-router-dom';
import { LoadingScreen } from '@/components/loading-screen';
import { ProtectedRoute } from '@/components/protected-route';
import { AppLayout } from '@/layouts/app-layout';
import { AccessDeniedPage } from '@/pages/auth/access-denied';
import { ForgotPasswordPage } from '@/pages/auth/forgot-password';
import { LoginPage } from '@/pages/auth/login';
import { RegisterPage } from '@/pages/auth/register';
import { SessionExpiredPage } from '@/pages/auth/session-expired';
import { DashboardPage } from '@/pages/dashboard';
import { DocumentListPage, DocumentFoldersPage, DocumentTagsPage, OcrQueuePage, DigitalSignaturesPage, DocumentCompliancePage, } from '@/pages/dms';
import { ErrorPage } from '@/pages/error-page';
import { AccountGroupsPage, ChartOfAccountsPage, LedgerMasterPage, JournalEntriesPage, CashBookPage, BankBookPage, CostCentersPage, AccountingSettingsPage, } from '@/pages/finance';
import { CreateAccountGroupPage, CreateChartOfAccountPage, CreateLedgerPage, CreateJournalEntryPage, CreateCostCenterPage, } from '@/pages/finance/dynamic-forms';
import { GlEntriesPage, PostingRulesPage, FiscalClosingPage, TrialBalancePage, ProfitLossPage, BalanceSheetPage, CashFlowPage, DayBookPage, AccountStatementPage, } from '@/pages/gl';
import { CreateGlEntryPage, CreatePostingRulePage, CreateFiscalClosingPage, } from '@/pages/gl/dynamic-forms';
import { GstRegistrationsPage, GstLedgerPage, GstReturnsPage, TaxPostingsPage, YearClosingPage, PeriodLocksPage, OpeningBalanceTransfersPage, YearEndEntriesPage, AuditDetailsPage, NumberSeriesPage, VoucherApprovalsPage, GstAuditSettingsPage, } from '@/pages/gst_audit';
import { CreateGstRegistrationPage, CreateTaxPostingPage, CreateNumberSeriesPage, } from '@/pages/gst_audit/dynamic-forms';
import { ItemsPage, ItemGroupsPage, ItemVariantsPage, ItemPricingPage, ItemBarcodesPage, HsnCodesPage, StockOpeningPage, ItemImagesPage, InventorySettingsPage, BatchesPage, StockMovementsPage, WarehouseLocationsPage, NearExpiryPage, DamageRegisterPage, RecallRegisterPage, DistributorReturnsPage, ReplacementQueuePage, InventorySummaryPage, StockLedgerPage, BatchLedgerPage, ExpiryReportPage, MovementReportPage, ValuationReportPage, DeadStockPage, FastMovingPage, SlowMovingPage, BarcodeGenPage, ProductsPage, CreateProductPage, EditProductPage, ProductDetailPage, SubCategoriesPage, NewStockEntryPage, StockAdjustmentPage, StockLedgerEnhancedPage, LocationTreePage, StockTransfersPage, CreateTransferPage, StockReservationPage, WarehouseReportsPage, } from '@/pages/inventory';
import { CompaniesPage, FinancialYearsPage, BranchesPage, WarehousesPage, UnitsPage, CategoriesPage, BrandsPage, TaxGroupsPage, GSTRatesPage, CreateCompanyPage, EditCompanyPage, CreateFinancialYearPage, EditFinancialYearPage, CreateBranchPage, EditBranchPage, CreateWarehousePage, EditWarehousePage, CreateUnitPage, EditUnitPage, CreateCategoryPage, EditCategoryPage, CreateBrandPage, EditBrandPage, CreateTaxGroupPage, EditTaxGroupPage, CreateGstRatePage, EditGstRatePage, } from '@/pages/masters';
import { NotFoundPage } from '@/pages/not-found-page';
import { PurchaseOrdersPage, PurchaseQuotationsPage, GrnPage, PurchaseInvoicesPage, PurchaseReturnsPage, SupplierPriceListPage, PurchaseApprovalsPage, PurchaseSettingsPage, SuppliersPage, CreateSupplierPage, EditSupplierPage, PurchaseRequisitionsPage, PurchaseRegisterReport, GrnRegisterReport, PendingPOReport, PurchaseReturnReport, GstPurchaseReport, } from '@/pages/purchase';
import { SalesQuotationsPage, SalesOrdersPage, DeliveryChallansPage, SalesInvoicesPage, SalesReturnsPage, CustomerPriceListPage, SalesApprovalsPage, SalesSettingsPage, CustomersPage, CreateCustomerPage, EditCustomerPage, } from '@/pages/sales';
import { ApprovalDashboardPage, PendingTasksDashboardPage, MyTasksDashboardPage, EscalationDashboardPage } from '@/pages/workflow';
const routes = [
    {
        path: '/',
        element: (_jsx(ProtectedRoute, { children: _jsx(AppLayout, {}) })),
        errorElement: _jsx(ErrorPage, {}),
        hydrateFallbackElement: _jsx(LoadingScreen, {}),
        children: [
            {
                index: true,
                element: _jsx(DashboardPage, {}),
            },
            // ── Master Data Modules ──────────────────────────
            // ── Master Data List Routes ────────────────────
            { path: 'companies', element: _jsx(CompaniesPage, {}) },
            { path: 'companies/create', element: _jsx(CreateCompanyPage, {}) },
            { path: 'companies/:id/edit', element: _jsx(EditCompanyPage, {}) },
            { path: 'financial-years', element: _jsx(FinancialYearsPage, {}) },
            { path: 'financial-years/create', element: _jsx(CreateFinancialYearPage, {}) },
            { path: 'financial-years/:id/edit', element: _jsx(EditFinancialYearPage, {}) },
            { path: 'branches', element: _jsx(BranchesPage, {}) },
            { path: 'branches/create', element: _jsx(CreateBranchPage, {}) },
            { path: 'branches/:id/edit', element: _jsx(EditBranchPage, {}) },
            { path: 'warehouses', element: _jsx(WarehousesPage, {}) },
            { path: 'warehouses/create', element: _jsx(CreateWarehousePage, {}) },
            { path: 'warehouses/:id/edit', element: _jsx(EditWarehousePage, {}) },
            { path: 'units', element: _jsx(UnitsPage, {}) },
            { path: 'units/create', element: _jsx(CreateUnitPage, {}) },
            { path: 'units/:id/edit', element: _jsx(EditUnitPage, {}) },
            { path: 'categories', element: _jsx(CategoriesPage, {}) },
            { path: 'categories/create', element: _jsx(CreateCategoryPage, {}) },
            { path: 'categories/:id/edit', element: _jsx(EditCategoryPage, {}) },
            { path: 'brands', element: _jsx(BrandsPage, {}) },
            { path: 'brands/create', element: _jsx(CreateBrandPage, {}) },
            { path: 'brands/:id/edit', element: _jsx(EditBrandPage, {}) },
            { path: 'tax-groups', element: _jsx(TaxGroupsPage, {}) },
            { path: 'tax-groups/create', element: _jsx(CreateTaxGroupPage, {}) },
            { path: 'tax-groups/:id/edit', element: _jsx(EditTaxGroupPage, {}) },
            { path: 'gst-rates', element: _jsx(GSTRatesPage, {}) },
            { path: 'gst-rates/create', element: _jsx(CreateGstRatePage, {}) },
            { path: 'gst-rates/:id/edit', element: _jsx(EditGstRatePage, {}) },
            // ── Inventory Modules ───────────────────────────
            { path: 'inventory/products', element: _jsx(ProductsPage, {}) },
            { path: 'inventory/products/create', element: _jsx(CreateProductPage, {}) },
            { path: 'inventory/products/:id/edit', element: _jsx(EditProductPage, {}) },
            { path: 'inventory/products/:id', element: _jsx(ProductDetailPage, {}) },
            { path: 'inventory/items', element: _jsx(ItemsPage, {}) },
            { path: 'inventory/groups', element: _jsx(ItemGroupsPage, {}) },
            { path: 'inventory/variants', element: _jsx(ItemVariantsPage, {}) },
            { path: 'inventory/pricing', element: _jsx(ItemPricingPage, {}) },
            { path: 'inventory/barcodes', element: _jsx(ItemBarcodesPage, {}) },
            { path: 'inventory/hsn-codes', element: _jsx(HsnCodesPage, {}) },
            { path: 'inventory/stock-opening', element: _jsx(StockOpeningPage, {}) },
            { path: 'inventory/sub-categories', element: _jsx(SubCategoriesPage, {}) },
            { path: 'inventory/images', element: _jsx(ItemImagesPage, {}) },
            { path: 'inventory/settings', element: _jsx(InventorySettingsPage, {}) },
            // ── PRM-015: Enterprise Inventory Engine ────
            { path: 'inventory/batches', element: _jsx(BatchesPage, {}) },
            { path: 'inventory/stock-entry', element: _jsx(NewStockEntryPage, {}) },
            { path: 'inventory/stock-adjustment', element: _jsx(StockAdjustmentPage, {}) },
            { path: 'inventory/ledger', element: _jsx(StockLedgerEnhancedPage, {}) },
            { path: 'inventory/stock-movements', element: _jsx(StockMovementsPage, {}) },
            { path: 'inventory/warehouse-dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'inventory/warehouse-locations', element: _jsx(WarehouseLocationsPage, {}) },
            { path: 'inventory/location-tree', element: _jsx(LocationTreePage, {}) },
            { path: 'inventory/stock-transfers', element: _jsx(StockTransfersPage, {}) },
            { path: 'inventory/create-transfer', element: _jsx(CreateTransferPage, {}) },
            { path: 'inventory/stock-reservation', element: _jsx(StockReservationPage, {}) },
            { path: 'inventory/near-expiry', element: _jsx(NearExpiryPage, {}) },
            { path: 'inventory/damage-register', element: _jsx(DamageRegisterPage, {}) },
            { path: 'inventory/recall-register', element: _jsx(RecallRegisterPage, {}) },
            { path: 'inventory/distributor-returns', element: _jsx(DistributorReturnsPage, {}) },
            { path: 'inventory/replacement-queue', element: _jsx(ReplacementQueuePage, {}) },
            { path: 'inventory/reports/summary', element: _jsx(InventorySummaryPage, {}) },
            { path: 'inventory/reports/stock-ledger', element: _jsx(StockLedgerPage, {}) },
            { path: 'inventory/reports/batch-ledger', element: _jsx(BatchLedgerPage, {}) },
            { path: 'inventory/reports/expiry', element: _jsx(ExpiryReportPage, {}) },
            { path: 'inventory/reports/movement', element: _jsx(MovementReportPage, {}) },
            { path: 'inventory/reports/valuation', element: _jsx(ValuationReportPage, {}) },
            { path: 'inventory/reports/warehouse', element: _jsx(WarehouseReportsPage, {}) },
            { path: 'inventory/reports/dead-stock', element: _jsx(DeadStockPage, {}) },
            { path: 'inventory/reports/fast-moving', element: _jsx(FastMovingPage, {}) },
            { path: 'inventory/reports/slow-moving', element: _jsx(SlowMovingPage, {}) },
            { path: 'inventory/barcode-gen', element: _jsx(BarcodeGenPage, {}) },
            // ── Purchase Modules ────────────────────────────
            { path: 'purchase/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'purchase/orders', element: _jsx(PurchaseOrdersPage, {}) },
            { path: 'purchase/quotations', element: _jsx(PurchaseQuotationsPage, {}) },
            { path: 'purchase/grn', element: _jsx(GrnPage, {}) },
            { path: 'purchase/invoices', element: _jsx(PurchaseInvoicesPage, {}) },
            { path: 'purchase/returns', element: _jsx(PurchaseReturnsPage, {}) },
            { path: 'purchase/supplier-prices', element: _jsx(SupplierPriceListPage, {}) },
            { path: 'purchase/approvals', element: _jsx(PurchaseApprovalsPage, {}) },
            { path: 'purchase/settings', element: _jsx(PurchaseSettingsPage, {}) },
            { path: 'suppliers', element: _jsx(SuppliersPage, {}) },
            { path: 'suppliers/create', element: _jsx(CreateSupplierPage, {}) },
            { path: 'suppliers/:id/edit', element: _jsx(EditSupplierPage, {}) },
            { path: 'purchase/requisitions', element: _jsx(PurchaseRequisitionsPage, {}) },
            { path: 'purchase/reports/purchase-register', element: _jsx(PurchaseRegisterReport, {}) },
            { path: 'purchase/reports/grn-register', element: _jsx(GrnRegisterReport, {}) },
            { path: 'purchase/reports/pending-pos', element: _jsx(PendingPOReport, {}) },
            { path: 'purchase/reports/purchase-returns', element: _jsx(PurchaseReturnReport, {}) },
            { path: 'purchase/reports/gst-purchase', element: _jsx(GstPurchaseReport, {}) },
            // ── Sales Modules ──────────────────────────────
            { path: 'sales/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'sales/quotations', element: _jsx(SalesQuotationsPage, {}) },
            { path: 'sales/orders', element: _jsx(SalesOrdersPage, {}) },
            { path: 'sales/delivery-challans', element: _jsx(DeliveryChallansPage, {}) },
            { path: 'sales/invoices', element: _jsx(SalesInvoicesPage, {}) },
            { path: 'sales/returns', element: _jsx(SalesReturnsPage, {}) },
            { path: 'sales/customer-prices', element: _jsx(CustomerPriceListPage, {}) },
            { path: 'sales/approvals', element: _jsx(SalesApprovalsPage, {}) },
            { path: 'customers', element: _jsx(CustomersPage, {}) },
            { path: 'customers/create', element: _jsx(CreateCustomerPage, {}) },
            { path: 'customers/:id/edit', element: _jsx(EditCustomerPage, {}) },
            { path: 'sales/settings', element: _jsx(SalesSettingsPage, {}) },
            // ── Finance Modules ────────────────────────────
            { path: 'finance/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'finance/account-groups', element: _jsx(AccountGroupsPage, {}) },
            { path: 'finance/account-groups/create', element: _jsx(CreateAccountGroupPage, {}) },
            { path: 'finance/account-groups/:id/edit', element: _jsx(CreateAccountGroupPage, {}) },
            { path: 'finance/chart-of-accounts', element: _jsx(ChartOfAccountsPage, {}) },
            { path: 'finance/chart-of-accounts/create', element: _jsx(CreateChartOfAccountPage, {}) },
            { path: 'finance/chart-of-accounts/:id/edit', element: _jsx(CreateChartOfAccountPage, {}) },
            { path: 'finance/ledgers', element: _jsx(LedgerMasterPage, {}) },
            { path: 'finance/ledgers/create', element: _jsx(CreateLedgerPage, {}) },
            { path: 'finance/ledgers/:id/edit', element: _jsx(CreateLedgerPage, {}) },
            { path: 'finance/journal-entries', element: _jsx(JournalEntriesPage, {}) },
            { path: 'finance/journal-entries/create', element: _jsx(CreateJournalEntryPage, {}) },
            { path: 'finance/journal-entries/:id/edit', element: _jsx(CreateJournalEntryPage, {}) },
            { path: 'finance/cash-book', element: _jsx(CashBookPage, {}) },
            { path: 'finance/bank-book', element: _jsx(BankBookPage, {}) },
            { path: 'finance/cost-centers', element: _jsx(CostCentersPage, {}) },
            { path: 'finance/cost-centers/create', element: _jsx(CreateCostCenterPage, {}) },
            { path: 'finance/cost-centers/:id/edit', element: _jsx(CreateCostCenterPage, {}) },
            { path: 'finance/settings', element: _jsx(AccountingSettingsPage, {}) },
            // ── GL / Reporting Modules ─────────────────────
            { path: 'gl/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'gl/entries', element: _jsx(GlEntriesPage, {}) },
            { path: 'gl/entries/create', element: _jsx(CreateGlEntryPage, {}) },
            { path: 'gl/entries/:id/edit', element: _jsx(CreateGlEntryPage, {}) },
            { path: 'gl/posting-rules', element: _jsx(PostingRulesPage, {}) },
            { path: 'gl/posting-rules/create', element: _jsx(CreatePostingRulePage, {}) },
            { path: 'gl/posting-rules/:id/edit', element: _jsx(CreatePostingRulePage, {}) },
            { path: 'gl/fiscal-closing', element: _jsx(FiscalClosingPage, {}) },
            { path: 'gl/fiscal-closing/create', element: _jsx(CreateFiscalClosingPage, {}) },
            { path: 'gl/fiscal-closing/:id/edit', element: _jsx(CreateFiscalClosingPage, {}) },
            { path: 'gl/trial-balance', element: _jsx(TrialBalancePage, {}) },
            { path: 'gl/profit-loss', element: _jsx(ProfitLossPage, {}) },
            { path: 'gl/balance-sheet', element: _jsx(BalanceSheetPage, {}) },
            { path: 'gl/cash-flow', element: _jsx(CashFlowPage, {}) },
            { path: 'gl/day-book', element: _jsx(DayBookPage, {}) },
            { path: 'gl/account-statement', element: _jsx(AccountStatementPage, {}) },
            // ── Automation Engine Modules ─────────────────
            { path: 'automation/posting', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'automation/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'automation/monitor', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'automation/integration', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'automation/health', element: _jsx(Navigate, { to: "/", replace: true }) },
            // ── GST, Audit & Financial Closing Modules ─────
            { path: 'gst/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'gst/analytics', element: _jsx(Navigate, { to: "/", replace: true }) },
            { path: 'gst/registrations', element: _jsx(GstRegistrationsPage, {}) },
            { path: 'gst/ledger', element: _jsx(GstLedgerPage, {}) },
            { path: 'gst/returns', element: _jsx(GstReturnsPage, {}) },
            { path: 'gst/tax-postings', element: _jsx(TaxPostingsPage, {}) },
            { path: 'gst/year-closing', element: _jsx(YearClosingPage, {}) },
            { path: 'gst/period-locks', element: _jsx(PeriodLocksPage, {}) },
            { path: 'gst/opening-balance-transfers', element: _jsx(OpeningBalanceTransfersPage, {}) },
            { path: 'gst/year-end-entries', element: _jsx(YearEndEntriesPage, {}) },
            { path: 'gst/audit-details', element: _jsx(AuditDetailsPage, {}) },
            { path: 'gst/registrations/create', element: _jsx(CreateGstRegistrationPage, {}) },
            { path: 'gst/registrations/:id/edit', element: _jsx(CreateGstRegistrationPage, {}) },
            { path: 'gst/tax-postings/create', element: _jsx(CreateTaxPostingPage, {}) },
            { path: 'gst/tax-postings/:id/edit', element: _jsx(CreateTaxPostingPage, {}) },
            { path: 'gst/number-series', element: _jsx(NumberSeriesPage, {}) },
            { path: 'gst/number-series/create', element: _jsx(CreateNumberSeriesPage, {}) },
            { path: 'gst/voucher-approvals', element: _jsx(VoucherApprovalsPage, {}) },
            { path: 'gst/settings', element: _jsx(GstAuditSettingsPage, {}) },
        ],
    }, // ── Old dashboards — all redirect to main dashboard ──
    { path: 'executive/ceo', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'executive/director', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'executive/admin', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'executive/operations', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'executive/user', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/purchase', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/sales', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/inventory', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/finance', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/gst', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/customers', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/suppliers', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/warehouses', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/profitability', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/cash-flow', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'bi/growth', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'dms/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'dms/documents', element: _jsx(DocumentListPage, {}) },
    { path: 'dms/folders', element: _jsx(DocumentFoldersPage, {}) },
    { path: 'dms/tags', element: _jsx(DocumentTagsPage, {}) },
    { path: 'dms/ocr', element: _jsx(OcrQueuePage, {}) },
    { path: 'dms/signatures', element: _jsx(DigitalSignaturesPage, {}) },
    { path: 'dms/compliance', element: _jsx(DocumentCompliancePage, {}) },
    { path: 'workflow/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'workflow/approvals', element: _jsx(ApprovalDashboardPage, {}) },
    { path: 'workflow/tasks', element: _jsx(PendingTasksDashboardPage, {}) },
    { path: 'workflow/my-tasks', element: _jsx(MyTasksDashboardPage, {}) },
    { path: 'workflow/escalation', element: _jsx(EscalationDashboardPage, {}) },
    { path: 'ai/dashboard', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'ai/insights', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'ai/forecasts', element: _jsx(Navigate, { to: "/", replace: true }) },
    { path: 'ai/usage', element: _jsx(Navigate, { to: "/", replace: true }) },
    // ── Auth Routes ──────────────────────────────────
    {
        path: '/auth',
        children: [
            { path: 'login', element: _jsx(LoginPage, {}) },
            { path: 'register', element: _jsx(RegisterPage, {}) },
            { path: 'forgot-password', element: _jsx(ForgotPasswordPage, {}) },
            { path: 'access-denied', element: _jsx(AccessDeniedPage, {}) },
            { path: 'session-expired', element: _jsx(SessionExpiredPage, {}) },
        ],
    },
    {
        path: '*',
        element: _jsx(NotFoundPage, {}),
    },
];
export const router = createBrowserRouter(routes);
//# sourceMappingURL=index.js.map