import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Wheat, TrendingUp, Minus } from 'lucide-react';
const placeholderCommodities = [
    { name: 'Soybean', symbol: 'SB', change: null },
    { name: 'Cotton', symbol: 'CT', change: null },
    { name: 'Wheat', symbol: 'WH', change: null },
    { name: 'Sugarcane', symbol: 'SC', change: null },
    { name: 'Maize', symbol: 'MZ', change: null },
];
export function CommodityPrices() {
    return (_jsxs("div", { className: "group relative overflow-hidden rounded-2xl border border-slate-100 bg-white p-6 transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5 dark:border-slate-800 dark:bg-slate-900", children: [_jsx("div", { className: "absolute -inset-1 bg-gradient-to-r from-teal-500 to-emerald-600 opacity-0 blur-xl transition-opacity duration-500 group-hover:opacity-5" }), _jsxs("div", { className: "relative", children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("div", { className: "flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-emerald-600 text-white shadow-md", children: _jsx(Wheat, { className: "h-4 w-4" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold text-slate-900 dark:text-white", children: "Commodity Prices" }), _jsx("p", { className: "text-[10px] text-slate-400 dark:text-slate-500", children: "Agriculture market" })] })] }), _jsx("div", { className: "mt-4 space-y-1.5", children: placeholderCommodities.map((c) => (_jsxs("div", { className: "flex items-center gap-3 rounded-xl border border-transparent p-2.5 transition-all hover:border-slate-100 hover:bg-slate-50/50 dark:hover:border-slate-700 dark:hover:bg-slate-800/30", children: [_jsx("div", { className: "flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-emerald-100 to-teal-100 text-xs font-bold text-emerald-700 dark:from-emerald-900/30 dark:to-teal-900/30 dark:text-emerald-400", children: c.symbol }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-xs font-medium text-slate-800 dark:text-slate-200", children: c.name }), _jsx("p", { className: "text-[10px] text-slate-400 dark:text-slate-500", children: "-- / quintal" })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm font-semibold text-slate-300 dark:text-slate-600", children: "--" }), _jsxs("span", { className: "inline-flex items-center gap-0.5 text-[10px] text-slate-300 dark:text-slate-600", children: [_jsx(Minus, { className: "h-2.5 w-2.5" }), " --"] })] })] }, c.name))) }), _jsx("div", { className: "relative mt-3 overflow-hidden rounded-xl border border-dashed border-slate-200 bg-slate-50/50 p-3 dark:border-slate-700 dark:bg-slate-800/20", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "flex h-6 w-6 items-center justify-center rounded-full bg-teal-100 dark:bg-teal-900/20", children: _jsx(TrendingUp, { className: "h-3 w-3 text-teal-600 dark:text-teal-400" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-[11px] font-medium text-slate-500 dark:text-slate-400", children: "Commodity feed coming soon" }), _jsx("p", { className: "text-[10px] text-slate-400 dark:text-slate-500", children: "Connect market data API for live prices" })] })] }) })] })] }));
}
//# sourceMappingURL=CommodityPrices.js.map