import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Purchase Analytics
// ═══════════════════════════════════════════════════════════════════
export function PurchaseAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Purchase Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Comprehensive purchase performance and trend analysis" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total POs', value: '—', color: 'border-l-blue-500' },
                    { label: 'Total Spend', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Avg PO Value', value: '₹—', color: 'border-l-purple-500' },
                    { label: 'Pending Deliveries', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Monthly Purchase Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Monthly purchase order value trend" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Top Suppliers by Spend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Top 10 suppliers by total spend" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Category Distribution" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Purchase by category" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "PO Status Overview" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 PO status breakdown (draft, approved, received, cancelled)" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Sales Analytics
// ═══════════════════════════════════════════════════════════════════
export function SalesAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Sales Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Real-time sales performance metrics and revenue analysis" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total Revenue', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Total Orders', value: '—', color: 'border-l-blue-500' },
                    { label: 'Avg Order Value', value: '₹—', color: 'border-l-purple-500' },
                    { label: 'Pending Invoices', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Revenue Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Monthly revenue trend line" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Top Customers" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Top 10 customers by revenue" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Product Performance" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Top-selling products" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Sales by Category" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Revenue by product category" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Inventory Analytics
// ═══════════════════════════════════════════════════════════════════
export function InventoryAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Inventory Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Stock movement, valuation, and turnover analysis" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total Items', value: '—', color: 'border-l-blue-500' },
                    { label: 'Stock Value', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Low Stock Items', value: '—', color: 'border-l-red-500' },
                    { label: 'Dead Stock', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Stock Movement" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Inward/outward stock movement over time" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Inventory Turnover" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Category-wise inventory turnover ratio" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Stock Aging" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Aging analysis of current stock" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Warehouse Distribution" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Stock distribution across warehouses" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Finance Analytics
// ═══════════════════════════════════════════════════════════════════
export function FinanceAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Finance Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Profitability, cash flow, and financial performance metrics" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Revenue', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Expenses', value: '₹—', color: 'border-l-red-500' },
                    { label: 'Net Profit', value: '₹—', color: 'border-l-blue-500' },
                    { label: 'Profit Margin', value: '—%', color: 'border-l-purple-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Income vs Expenses" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Monthly income vs expense comparison" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Cash Flow" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Operating, investing, financing cash flow" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Expense Breakdown" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Expense by category" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Profit Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Gross vs net profit trend" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — GST Analytics
// ═══════════════════════════════════════════════════════════════════
export function GstAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "GST Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Tax liability, input credit, and GST filing overview" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Output GST', value: '₹—', color: 'border-l-red-500' },
                    { label: 'Input Credit', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Net Payable', value: '₹—', color: 'border-l-blue-500' },
                    { label: 'Pending Returns', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "GST Liability Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Monthly GST payable trend" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "ITC vs Output" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Input tax credit vs output tax comparison" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "GST Rate Distribution" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Taxable value by GST rate slab" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Filing Status" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 GST return filing status overview" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Customer Analytics
// ═══════════════════════════════════════════════════════════════════
export function CustomerAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Customer Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Customer segmentation, behavior, and revenue analysis" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total Customers', value: '—', color: 'border-l-blue-500' },
                    { label: 'Active Customers', value: '—', color: 'border-l-green-500' },
                    { label: 'Avg Revenue/Customer', value: '₹—', color: 'border-l-purple-500' },
                    { label: 'Repeat Rate', value: '—%', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Customer Distribution" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Customers by region/category" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Revenue by Customer" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Top customers by revenue contribution" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Supplier Analytics
// ═══════════════════════════════════════════════════════════════════
export function SupplierAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Supplier Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Supplier performance, spending, and reliability metrics" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total Suppliers', value: '—', color: 'border-l-blue-500' },
                    { label: 'Active Suppliers', value: '—', color: 'border-l-green-500' },
                    { label: 'Total Spend', value: '₹—', color: 'border-l-purple-500' },
                    { label: 'Avg Delivery Days', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Spend by Supplier" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Top suppliers by spend" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Supplier Performance" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 On-time delivery rate by supplier" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// BI ANALYTICS DASHBOARD — Warehouse Analytics
// ═══════════════════════════════════════════════════════════════════
export function WarehouseAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Warehouse Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Warehouse capacity, utilization, and efficiency metrics" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Total Warehouses', value: '—', color: 'border-l-blue-500' },
                    { label: 'Total Capacity', value: '—', color: 'border-l-green-500' },
                    { label: 'Utilization', value: '—%', color: 'border-l-purple-500' },
                    { label: 'Items in Stock', value: '—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Warehouse Utilization" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Capacity utilization by warehouse" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Stock Distribution" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Stock value distribution across warehouses" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// PROFITABILITY ANALYTICS
// ═══════════════════════════════════════════════════════════════════
export function ProfitabilityAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Profitability Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Gross profit, net profit, margin analysis across dimensions" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Gross Profit', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Net Profit', value: '₹—', color: 'border-l-blue-500' },
                    { label: 'Gross Margin', value: '—%', color: 'border-l-purple-500' },
                    { label: 'Net Margin', value: '—%', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Margin Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Gross and net margin trend over time" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Profit by Product" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Profit contribution by product category" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// CASH FLOW ANALYTICS
// ═══════════════════════════════════════════════════════════════════
export function CashFlowAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Cash Flow Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Cash inflow/outflow analysis and liquidity forecasting" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Operating Cash Flow', value: '₹—', color: 'border-l-green-500' },
                    { label: 'Investing Cash Flow', value: '₹—', color: 'border-l-blue-500' },
                    { label: 'Financing Cash Flow', value: '₹—', color: 'border-l-purple-500' },
                    { label: 'Net Cash Flow', value: '₹—', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Cash Flow Trend" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Monthly cash flow trend (inflow vs outflow)" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Cash Position" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Opening vs closing cash balance over time" })] })] })] }));
}
// ═══════════════════════════════════════════════════════════════════
// GROWTH ANALYTICS
// ═══════════════════════════════════════════════════════════════════
export function GrowthAnalyticsPage() {
    return (_jsxs("div", { className: "space-y-6 p-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight", children: "Growth Analytics" }), _jsx("p", { className: "mt-1 text-sm text-muted-foreground", children: "Year-over-year growth, trends, and business expansion metrics" })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [
                    { label: 'Revenue Growth', value: '—%', color: 'border-l-green-500' },
                    { label: 'Order Growth', value: '—%', color: 'border-l-blue-500' },
                    { label: 'Customer Growth', value: '—%', color: 'border-l-purple-500' },
                    { label: 'Market Share', value: '—%', color: 'border-l-yellow-500' },
                ].map((c) => (_jsxs("div", { className: `rounded-lg border-l-4 bg-card p-4 shadow-sm ${c.color}`, children: [_jsx("p", { className: "text-sm font-medium text-muted-foreground", children: c.label }), _jsx("p", { className: "mt-1 text-2xl font-bold", children: c.value })] }, c.label))) }), _jsxs("div", { className: "grid gap-6 lg:grid-cols-2", children: [_jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "YoY Revenue Growth" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Year-over-year revenue comparison" })] }), _jsxs("div", { className: "rounded-lg border bg-card p-6 shadow-sm", children: [_jsx("h2", { className: "mb-4 font-semibold", children: "Growth Drivers" }), _jsx("div", { className: "flex h-48 items-center justify-center rounded-md bg-muted/50 text-sm text-muted-foreground", children: "Chart \u2014 Growth contribution by product line" })] })] })] }));
}
//# sourceMappingURL=index.js.map