export declare function ItemsPage(): import("react").JSX.Element;
export declare function ItemGroupsPage(): import("react").JSX.Element;
export declare function ItemVariantsPage(): import("react").JSX.Element;
export declare function ItemPricingPage(): import("react").JSX.Element;
export declare function ItemBarcodesPage(): import("react").JSX.Element;
export declare function HsnCodesPage(): import("react").JSX.Element;
export declare function StockOpeningPage(): import("react").JSX.Element;
export declare function ItemImagesPage(): import("react").JSX.Element;
export declare function InventorySettingsPage(): import("react").JSX.Element;
export { BatchesPage } from './batches';
export { StockMovementsPage } from './stock-movements';
export { WarehouseLocationsPage } from './warehouse-locations';
export { NearExpiryPage, DamageRegisterPage, RecallRegisterPage, DistributorReturnsPage, ReplacementQueuePage } from './agriculture';
export { InventorySummaryPage, StockLedgerPage, BatchLedgerPage, ExpiryReportPage, MovementReportPage, ValuationReportPage, WarehouseReportPage, DeadStockPage, FastMovingPage, SlowMovingPage } from './reports';
export { BarcodeGenPage } from './barcode-gen';
export { ProductsPage } from './products';
export { ProductDetailPage } from './product-detail';
export { SubCategoriesPage } from './sub-categories';
export { NewStockEntryPage } from './stock-entry';
export { StockAdjustmentPage } from './stock-adjustment';
export { StockLedgerEnhancedPage } from './stock-ledger-enhanced';
export { WarehouseDashboardPage } from './warehouse-dashboard';
export { LocationTreePage } from './location-tree';
export { StockTransfersPage, CreateTransferPage } from './stock-transfers';
export { StockReservationPage } from './stock-reservation';
export { WarehouseReportsPage } from './warehouse-reports';
export { CreateProductPage, EditProductPage } from './product-form';
//# sourceMappingURL=index.d.ts.map