"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.booleanColumn = exports.yesNoEnum = exports.statusColumn = exports.statusEnum = exports.pgBaseSchema = exports.sqliteBaseSchema = exports.pgAuditColumns = exports.sqliteAuditColumns = exports.pgSoftDelete = exports.sqliteSoftDelete = exports.pgTimestamps = exports.sqliteTimestamps = exports.pgId = exports.sqliteId = exports.pgTable = exports.sqliteTable = void 0;
var helpers_1 = require("./helpers");
Object.defineProperty(exports, "sqliteTable", { enumerable: true, get: function () { return helpers_1.sqliteTable; } });
Object.defineProperty(exports, "pgTable", { enumerable: true, get: function () { return helpers_1.pgTable; } });
Object.defineProperty(exports, "sqliteId", { enumerable: true, get: function () { return helpers_1.sqliteId; } });
Object.defineProperty(exports, "pgId", { enumerable: true, get: function () { return helpers_1.pgId; } });
Object.defineProperty(exports, "sqliteTimestamps", { enumerable: true, get: function () { return helpers_1.sqliteTimestamps; } });
Object.defineProperty(exports, "pgTimestamps", { enumerable: true, get: function () { return helpers_1.pgTimestamps; } });
Object.defineProperty(exports, "sqliteSoftDelete", { enumerable: true, get: function () { return helpers_1.sqliteSoftDelete; } });
Object.defineProperty(exports, "pgSoftDelete", { enumerable: true, get: function () { return helpers_1.pgSoftDelete; } });
Object.defineProperty(exports, "sqliteAuditColumns", { enumerable: true, get: function () { return helpers_1.sqliteAuditColumns; } });
Object.defineProperty(exports, "pgAuditColumns", { enumerable: true, get: function () { return helpers_1.pgAuditColumns; } });
Object.defineProperty(exports, "sqliteBaseSchema", { enumerable: true, get: function () { return helpers_1.sqliteBaseSchema; } });
Object.defineProperty(exports, "pgBaseSchema", { enumerable: true, get: function () { return helpers_1.pgBaseSchema; } });
Object.defineProperty(exports, "statusEnum", { enumerable: true, get: function () { return helpers_1.statusEnum; } });
Object.defineProperty(exports, "statusColumn", { enumerable: true, get: function () { return helpers_1.statusColumn; } });
Object.defineProperty(exports, "yesNoEnum", { enumerable: true, get: function () { return helpers_1.yesNoEnum; } });
Object.defineProperty(exports, "booleanColumn", { enumerable: true, get: function () { return helpers_1.booleanColumn; } });
//# sourceMappingURL=index.js.map