import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
export const ForecastWidget = ({ title, metric, unit, currentValue, forecastValue, changePercent, data, }) => {
    const isUp = changePercent > 0;
    const isDown = changePercent < 0;
    const maxVal = Math.max(...data.map(d => Math.max(d.actual || 0, d.predicted)));
    return (_jsxs("div", { className: "rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900", children: [_jsx("h4", { className: "text-sm font-semibold text-gray-900 dark:text-white", children: title }), _jsx("p", { className: "text-xs text-gray-500 mt-0.5", children: metric }), _jsxs("div", { className: "mt-3 flex items-end gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[10px] text-gray-400 uppercase", children: "Current" }), _jsxs("p", { className: "text-xl font-bold text-gray-900 dark:text-white", children: [unit, currentValue.toLocaleString()] })] }), _jsxs("div", { className: "flex items-center gap-1 mb-1", children: [isUp ? _jsx(TrendingUp, { className: "h-4 w-4 text-green-500" }) : isDown ? _jsx(TrendingDown, { className: "h-4 w-4 text-red-500" }) : _jsx(Minus, { className: "h-4 w-4 text-gray-400" }), _jsxs("span", { className: `text-sm font-semibold ${isUp ? 'text-green-600' : isDown ? 'text-red-600' : 'text-gray-500'}`, children: [changePercent > 0 ? '+' : '', changePercent.toFixed(1), "%"] })] })] }), _jsxs("div", { className: "mt-3", children: [_jsx("p", { className: "text-[10px] text-gray-400 uppercase", children: "Forecast" }), _jsxs("p", { className: "text-lg font-bold text-blue-600 dark:text-blue-400", children: [unit, forecastValue.toLocaleString()] })] }), _jsx("div", { className: "mt-3 flex items-end gap-1 h-16", children: data.slice(-8).map((point, i) => {
                    const actualH = point.actual ? (point.actual / maxVal) * 100 : 0;
                    const forecastH = (point.predicted / maxVal) * 100;
                    return (_jsxs("div", { className: "flex-1 flex flex-col items-center justify-end gap-0.5", children: [point.actual !== undefined && (_jsx("div", { className: "w-full rounded-t-sm bg-blue-500", style: { height: `${actualH}%` }, title: `Actual: ${point.actual}` })), _jsx("div", { className: `w-full rounded-t-sm ${point.actual !== undefined ? 'bg-blue-300' : 'bg-blue-400'}`, style: { height: `${forecastH}%`, opacity: point.actual !== undefined ? 0.5 : 1 }, title: `Predicted: ${point.predicted}` })] }, i));
                }) }), _jsxs("div", { className: "mt-2 flex items-center gap-3 text-[10px] text-gray-400", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx("div", { className: "h-2 w-2 rounded-sm bg-blue-500" }), _jsx("span", { children: "Actual" })] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("div", { className: "h-2 w-2 rounded-sm bg-blue-300 opacity-50" }), _jsx("span", { children: "Predicted" })] })] })] }));
};
//# sourceMappingURL=ForecastWidget.js.map