import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, Save, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { Breadcrumb } from './Breadcrumb';
import { Button } from './Button';
import { FormCard } from './FormCard';
export function CreateEditPage({ title, description, module, listPath, sections, isEditing, loading, submitting, error, onSave, onSaveDraft, onSaveNew, onCancel, showDraft = false, showSaveNew = false, }) {
    const navigate = useNavigate();
    const breadcrumbs = [
        { label: 'Dashboard', path: '/' },
        { label: module, path: listPath || `/${module.toLowerCase().replace(/\s+/g, '-')}` },
        { label: isEditing ? `Edit ${title}` : `Create ${title}` },
    ];
    const handleCancel = onCancel || (() => navigate(-1));
    if (loading) {
        return (_jsxs("div", { className: "space-y-6 animate-in fade-in duration-300", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "h-4 w-48 animate-pulse rounded bg-slate-200 dark:bg-slate-700" }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "h-8 w-64 animate-pulse rounded bg-slate-200 dark:bg-slate-700" }), _jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "h-10 w-24 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-700" }), _jsx("div", { className: "h-10 w-32 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-700" })] })] })] }), _jsx("div", { className: "grid gap-6 md:grid-cols-2", children: [1, 2].map((card) => (_jsxs("div", { className: "rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-700 dark:bg-slate-800/50", children: [_jsx("div", { className: "h-5 w-32 animate-pulse rounded bg-slate-200 dark:bg-slate-700" }), _jsx("div", { className: "mt-4 space-y-3", children: [1, 2, 3].map((f) => (_jsx("div", { className: "h-[42px] animate-pulse rounded-xl bg-slate-100 dark:bg-slate-700" }, f))) })] }, card))) })] }));
    }
    return (_jsxs("div", { className: "space-y-6 animate-in fade-in duration-300", children: [_jsx(Breadcrumb, { items: breadcrumbs }), error && (_jsxs("div", { className: "flex items-center gap-2.5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950 dark:text-red-400", children: [_jsx(X, { className: "h-4 w-4 shrink-0" }), error] })), _jsxs("div", { className: "flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("button", { type: "button", onClick: handleCancel, className: "mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-500 transition-all hover:bg-slate-50 hover:text-slate-700 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700", children: _jsx(ArrowLeft, { className: "h-4 w-4" }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100", children: isEditing ? `Edit ${title}` : `Create ${title}` }), description && (_jsx("p", { className: "mt-1 text-sm text-slate-500 dark:text-slate-400", children: description }))] })] }), _jsxs("div", { className: "flex items-center gap-3 shrink-0", children: [_jsx(Button, { variant: "secondary", onClick: handleCancel, icon: _jsx(X, { className: "h-4 w-4" }), children: "Cancel" }), showDraft && onSaveDraft && (_jsx(Button, { variant: "outline", loading: submitting, onClick: onSaveDraft, children: "Save Draft" })), showSaveNew && onSaveNew && (_jsx(Button, { variant: "secondary", loading: submitting, onClick: onSaveNew, children: "Save & New" })), _jsx(Button, { variant: "primary", loading: submitting, icon: _jsx(Save, { className: "h-4 w-4" }), onClick: onSave, children: isEditing ? 'Update' : 'Save' })] })] }), _jsx("div", { className: "grid gap-8 md:grid-cols-2", children: sections.map((section, idx) => (_jsx(FormCard, { title: section.title, description: section.description, className: section.className, children: _jsx("div", { className: cn('space-y-4', section.className), children: section.fields }) }, idx))) })] }));
}
//# sourceMappingURL=CreateEditPage.js.map