CREATE TABLE `shranix_purchase_invoice_items` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`deleted_at` text,
	`is_deleted` integer DEFAULT false NOT NULL,
	`invoice_id` text NOT NULL,
	`po_item_id` text,
	`grn_item_id` text,
	`item_id` text NOT NULL,
	`variant_id` text,
	`batch_no` text,
	`mfg_date` text,
	`exp_date` text,
	`quantity` real DEFAULT 1 NOT NULL,
	`unit_id` text,
	`rate` real DEFAULT 0 NOT NULL,
	`discount_percent` real DEFAULT 0 NOT NULL,
	`discount_amount` real DEFAULT 0 NOT NULL,
	`taxable_value` real DEFAULT 0 NOT NULL,
	`gst_rate` real DEFAULT 0 NOT NULL,
	`igst` real DEFAULT 0 NOT NULL,
	`cgst` real DEFAULT 0 NOT NULL,
	`sgst` real DEFAULT 0 NOT NULL,
	`cess` real DEFAULT 0 NOT NULL,
	`total_amount` real DEFAULT 0 NOT NULL,
	`warehouse_id` text,
	`remarks` text
);
